export const GET_COUNTRY_TOP_NEWS = 'GET_COUNTRY_TOP_NEWS';
export const GET_COUNTRY_TOP_NEWS_BY_CATEGORIES = 'GET_COUNTRY_TOP_NEWS_BY_CATEGORIES';
export const GET_CATEGORY_TOP_NEWS = 'GET_CATEGORY_TOP_NEWS';
export const SET_COUNTRY = 'SET_COUNTRY';
export const DISABLE_COUNTRY_SELECTION = 'DISABLE_COUNTRY_SELECTION';
export const GET_ERRORS = 'GET_ERRORS';